name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: devdeploy-dashboard

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React App
        working-directory: ./frontend
        run: npm run build

      - name: Check build output
        run: ls -la frontend/dist

      - name: Build Docker Image
        run: docker build -f docker/Dockerfile -t $IMAGE_NAME .

      # 🔍 DEBUG (correct syntax)
      - name: Debug Docker Username
        run: echo "USERNAME=${{ secrets.DOCKER_NAME }}"

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_NAME }}" --password-stdin

      - name: Tag Image
        run: docker tag $IMAGE_NAME ${{ secrets.DOCKER_NAME }}/$IMAGE_NAME:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_NAME }}/$IMAGE_NAME:latest

      - name: Done
        run: echo "CI/CD completed successfully 🚀"